swagger: '2.0'
info:
  title: Kathra Core Model
  version: 1.3.0-SNAPSHOT
  x-artifactName: core
  x-groupId: org.kathra
paths: 
  /no-operation:
    get:
      summary: "empty"
      operationId: "empty"
      produces:
        - "application/json"
      parameters: []
      responses:
        200:
          description: "empty"
          schema:
            type: "string"
definitions:
  BinaryRepositoryType:
    type: string
    enum: &BinaryRepositoryType
    - JAVA
    - PYTHON
    - DOCKER_IMAGE
    - HELM
  PACKAGE_TEMPLATE:
    type: string
    enum: &PACKAGE_TEMPLATE
    - REST_SERVICE
  PACKAGE_TYPE:
    type: string
    enum: &PACKAGE_TYPE
    - HELM
    - KUSTOMIZE
    - APT
    - SNAP
  MEMBERSHIP_ROLE:
    type: string
    enum: &MEMBERSHIP_ROLE
    - GUEST
    - CONTRIBUTOR
    - MANAGER
  MEMBERSHIP_MEMBERTYPE:
    type: string
    enum: &MEMBERSHIP_MEMBERTYPE
    - USER
    - GROUP
  PROGRAMMING_LANGUAGE:
    type: string
    enum: &PROGRAMMING_LANGUAGE
    - JAVA
    - PYTHON
  LIBRARY_TYPE:
    type: string
    enum: &LIBRARY_TYPE
    - MODEL
    - INTERFACE
    - CLIENT
  API_REPOSITORY_SATUS:
    type: string
    enum: &API_REPOSITORY_SATUS
    - PENDING
    - READY
    - UPDATING
    - UNSTABLE
    - ERROR
    - DELETED
  PIPELINE_TEMPLATE:
    type: string
    enum: &PIPELINE_TEMPLATE
    - JAVA_LIBRARY
    - PYTHON_SERVICE
    - JAVA_SERVICE
    - PYTHON_LIBRARY
    - HELM_PACKAGE
    - DOCKER_SERVICE
  BUILD_STATUS:
    type: string
    enum: &BUILD_STATUS
    - scheduled
    - processing
    - success
    - failed
  RESOURCE_STATUS:
    type: string
    enum: &RESOURCE_STATUS
    - PENDING
    - READY
    - UPDATING
    - UNSTABLE
    - ERROR
    - DELETED
  RuntimeJobStatus:
    type: string
    enum: &RuntimeJobStatus
    - SCHEDULED
    - RUNNING
    - SUCCESS
    - FAILED
  RuntimeAppInstanceStatus:
    type: string
    enum: &RuntimeAppInstanceStatus
    - DEPLOYED
    - PENDING
    - FAILED
  RuntimeVolumeStatus:
    type: string
    enum: &RuntimeVolumeStatus
    - PROVISIONING
    - AVAILABLE
    - TERMINATING
  RuntimeContainerStatus:
    type: string
    enum: &RuntimeContainerStatus
    - CREATING
    - RUNNING
    - PAUSED
    - TERMINATING
    - EXIT_WITH_SUCCES
    - EXIT_WITH_ERROR
  RuntimeEnvironmentBackupStatus:
    type: string
    enum: &RuntimeEnvironmentBackupStatus
    - SCHEDULED
    - PROCESSING
    - DONE
    - FAILED
  ApiVersion:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        component:
          $ref: '#/definitions/Component'
        version:
          type: string
        released:
          type: boolean
        apiRepositoryStatus:
          enum: *RESOURCE_STATUS
        implementationsVersions:
          type: array
          items:
            $ref: '#/definitions/ImplementationVersion'
        librariesApiVersions:
          type: array
          items:
            $ref: '#/definitions/LibraryApiVersion'
  Asset:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        binaryRepository:
          $ref: '#/definitions/BinaryRepository'
        sourceRepository:
          $ref: '#/definitions/SourceRepository'
        pipeline:
          $ref: '#/definitions/Pipeline'
  BinaryRepository:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        type:
          enum: *BinaryRepositoryType
        url:
          type: string
        provider:
          type: string
        providerId:
          type: string
        snapshot:
          type: boolean
        group:
          $ref: '#/definitions/Group'
  CatalogEntry:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        packageTemplate:
          enum: *PACKAGE_TEMPLATE
        packages:
          type: array
          items:
            $ref: '#/definitions/CatalogEntryPackage'
        description:
          type: string
  CatalogEntryPackage:
    allOf:
    - $ref: '#/definitions/Asset'
    - type: object
      properties:
        catalogEntry:
          $ref: '#/definitions/CatalogEntry'
        packageType:
          enum: *PACKAGE_TYPE
        provider:
          type: string
        providerId:
          type: string
        url:
          type: string
        versions:
          type: array
          items:
            $ref: '#/definitions/CatalogEntryPackageVersion'
  PackageTemplate:
    type: object
    properties:
      name:
          type: string
      arguments:
          type: array
          items:
            $ref: '#/definitions/PackageTemplateArgument'
  PackageTemplateArgument:
    type: object
    properties:
      key:
          type: string
      value:
          type: string
      constraint:
          type: string
  CatalogEntryPackageVersion:
    type: object
    properties:
      version:
          type: string
      documentation:
          type: string
      catalogEntryPackage:
          $ref: '#/definitions/CatalogEntryPackage'
      arguments:
          type: array
          items:
            $ref: '#/definitions/CatalogEntryArgument'
  CatalogEntryArgument:
    type: object
    properties:
      label:
          type: string
      description:
          type: string
      key:
          type: string
      value:
          type: string
      constraint:
          type: string
  Component:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        description:
          type: string
        title:
          type: string
        apiRepository:
          $ref: '#/definitions/SourceRepository'
        versions:
          type: array
          items:
            $ref: '#/definitions/ApiVersion'
        implementations:
          type: array
          items:
            $ref: '#/definitions/Implementation'
        libraries:
          type: array
          items:
            $ref: '#/definitions/Library'
  Group:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        path:
          type: string
        parent:
          $ref: '#/definitions/Group'
        technicalUser:
          $ref: '#/definitions/User'
        binaryRepositories:
          type: array
          items:
            $ref: '#/definitions/BinaryRepository'
        members:
          type: array
          items:
            $ref: '#/definitions/Assignation'
        sourceRepositoryStatus:
          enum: *RESOURCE_STATUS
        sourceMembershipStatus:
          enum: *RESOURCE_STATUS
        pipelineFolderStatus:
          enum: *RESOURCE_STATUS
        binaryRepositoryStatus:
          enum: *RESOURCE_STATUS
  Membership:
    type: object
    properties:
      path:
          type: string
      role:
          enum: *MEMBERSHIP_ROLE
      memberType:
          enum: *MEMBERSHIP_MEMBERTYPE
      memberName:
          type: string
  Assignation:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        role:
          type: string
        fte:
          type: string
  Implementation:
    allOf:
    - $ref: '#/definitions/Asset'
    - type: object
      properties:
        description:
          type: string
        title:
          type: string
        component:
          $ref: '#/definitions/Component'
        versions:
          type: array
          items:
            $ref: '#/definitions/ImplementationVersion'
        catalogEntries:
          type: array
          items:
            $ref: '#/definitions/CatalogEntry'
        language:
          enum: *PROGRAMMING_LANGUAGE
  ImplementationVersion:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        version:
          type: string
        description:
          type: string
        implementation:
          $ref: '#/definitions/Implementation'
        apiVersion:
          $ref: '#/definitions/ApiVersion'
        sourceRepo:
          $ref: '#/definitions/SourceRepository'
  KeyPair:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        privateKey:
          type: string
        publicKey:
          type: string
        group:
          $ref: '#/definitions/Group'
  Library:
    allOf:
    - $ref: '#/definitions/Asset'
    - type: object
      properties:
        type:
          enum: *LIBRARY_TYPE
        component:
          $ref: '#/definitions/Component'
        versions:
          type: array
          items:
            $ref: '#/definitions/LibraryApiVersion'
        language:
          enum: *PROGRAMMING_LANGUAGE
  LibraryApiVersion:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        apiVersion:
          $ref: '#/definitions/ApiVersion'
        library:
          $ref: '#/definitions/Library'
        apiRepositoryStatus:
          enum: *API_REPOSITORY_SATUS
        pipelineStatus:
          enum: *RESOURCE_STATUS
  Pipeline:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        provider:
          type: string
        providerId:
          type: string
        credentialId:
          type: string
        sourceRepository:
          $ref: '#/definitions/SourceRepository'
        path:
          type: string
        template:
          enum: *PIPELINE_TEMPLATE
  Build:
    type: object
    properties:
      buildNumber:
          type: string
      path:
          type: string
      commitLabel:
          type: string
      commitId:
          type: string
      creationDate:
          type: integer
          format: int64
      duration:
          type: integer
          format: int32
      status:
          enum: *BUILD_STATUS
      buildArguments:
          type: array
          items:
            $ref: '#/definitions/BuildArgument'
      logs:
          type: string
  BuildArgument:
    type: object
    properties:
      key:
          type: string
      value:
          type: string
  Resource:
    type: object
    properties:
      id:
          type: string
      name:
          type: string
      metadata:
          type: object
          additionalProperties:
            type: object
      status:
          enum: *RESOURCE_STATUS
      createdBy:
          type: string
      updatedBy:
          type: string
      createdAt:
          type: integer
          format: int32
      updatedAt:
          type: integer
          format: int32
  Cluster:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        providerId:
          type: string
        provider:
          type: string
        packageManagerManaged:
          enum: *PACKAGE_TYPE
  RuntimeEnvironment:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        providerId:
          type: string
        provider:
          type: string
        description:
          type: string
        labels:
          type: string
        owner:
          $ref: '#/definitions/User'
  RuntimeAppInstance:
    type: object
    properties:
      providerId:
          type: string
      name:
          type: string
      status:
          enum: *RuntimeAppInstanceStatus
  RuntimeJob:
    type: object
    properties:
      providerId:
          type: string
      status:
          enum: *RuntimeAppInstanceStatus
  RuntimeAppService:
    type: object
    properties:
      name:
          type: string
      providerId:
          type: string
      status:
          type: object
          additionalProperties:
            type: object
  RuntimeVolume:
    type: object
    properties:
      name:
          type: string
      providerId:
          type: string
      space:
          type: string
      status:
          enum: *RuntimeJobStatus
  RuntimeContainer:
    type: object
    properties:
      name:
          type: string
      providerId:
          type: string
      image:
          type: string
      imageHash:
          type: string
      memoryLimit:
          type: string
      cpuLimit:
          type: string
      status:
          enum: *RuntimeContainerStatus
  RuntimeEnvironmentBackup:
    type: object
    properties:
      date:
          type: string
      providerId:
          type: string
      status:
          type: string
  RuntimeHttpLoadBalancer:
    type: object
    properties:
      name:
          type: string
      providerId:
          type: string
      hostname:
          type: string
      port:
          type: string
      rewriteUrl:
          type: string
  RuntimeHttpLoadBalancerForwarding:
    type: object
    properties:
      rule:
          type: string
      service:
          type: string
      port:
          type: string
  SourceRepository:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        provider:
          type: string
        providerId:
          type: string
        path:
          type: string
        sshUrl:
          type: string
        httpUrl:
          type: string
        webUrl:
          type: string
        branchs:
          type: array
          items:
            type: string
  SourceRepositoryCommit:
    type: object
    properties:
      id:
          type: string
      shortId:
          type: string
      title:
          type: string
      authorName:
          type: string
      authorEmail:
          type: string
      createdAt:
          type: string
      committerName:
          type: string
      committerEmail:
          type: string
      message:
          type: string
  User:
    allOf:
    - $ref: '#/definitions/Resource'
    - type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        groups:
          type: array
          items:
            $ref: '#/definitions/Assignation'
