@startuml

class  ApiVersion {
  Component component
  String version
  Boolean released
  RESOURCE_STATUS apiRepositoryStatus
  ListOfImplementationVersion implementationsVersions
  ListOfLibraryApiVersion librariesApiVersions
}
Component "1" *-- "0..*"  ApiVersion
Resource <|-- ApiVersion
@enduml