@startuml

class  SourceRepository {
  String provider
  String providerId
  String path
  String sshUrl
  String httpUrl
  String webUrl
  ListOfString branchs
}
Resource <|-- SourceRepository

class SourceRepositoryCommit {
  String id
  String shortId
  String title
  String authorName
  String authorEmail
  String createdAt
  String committerName
  String committerEmail
  String message
  
}

@enduml
