@startuml

activate AppManager.BinaryRepositoryService
    AppManager.BinaryRepositoryService -> BinaryRepositoryManager: GET /credentials/{id} [id: user.name]
    activate BinaryRepositoryManager
    BinaryRepositoryManager -> Harbor : Retreive or generate new cliSecret
    activate Harbor
    BinaryRepositoryManager <- Harbor : Return cliSecret
    deactivate Harbor
    AppManager.BinaryRepositoryService <- BinaryRepositoryManager : Credential  w/ username and password
    deactivate BinaryRepositoryManager
    "BinaryRepositoryServiceCaller" <- AppManager.BinaryRepositoryService  :  Credential w/ username and password
deactivate AppManager.BinaryRepositoryService


@enduml