@startuml

class  BinaryRepository {
     BinaryRepositoryType type
     String url
     String provider
     String providerId
     Boolean snapshot
     Group group
}
Resource <|-- BinaryRepository

enum  BinaryRepositoryType {
     JAVA
     PYTHON
     DOCKER_IMAGE
     HELM
}

BinaryRepository  "0..*" --o "1" Asset : binaryRepository
Group  "0..*" --o "1" BinaryRepository : group

@enduml