@startuml

class  BinaryRepository {
     BinaryRepositoryType binaryRepositoryType
     String url
     String provider
     String providerId
     Boolean snapshot
}

enum  BinaryRepositoryType {
     JAVA
     PYTHON
     DOCKER
     HELM
}

BinaryRepository  "0..*" --o "1" Asset : binaryRepository
Group  "0..*" --o "1" BinaryRepository : group

@enduml