@startuml
hide empty members
set namespaceSeparator none

skinparam class {
	BackgroundColor PaleGreen
	ArrowColor RoyalBlue
	BorderColor DimGray
}

!include ./ApiVersion/model.puml
!include ./Asset/model.puml
!include ./BinaryRepository/model.puml
!include ./CatalogEntry/model.puml
!include ./CatalogEntryPackage/model.puml
!include ./CatalogEntryPackageVersion/model.puml
!include ./Component/model.puml
!include ./Group/model.puml
!include ./Implementation/model.puml
!include ./KeyPair/model.puml
!include ./Library/model.puml
!include ./Pipeline/model.puml
!include ./Resource/model.puml
!include ./RuntimeEnvironment/model.puml
!include ./SourceRepository/model.puml
!include ./User/model.puml


@enduml