@startuml
class  Pipeline {
  String provider
  String providerId
  String credentialId
  SourceRepository sourceRepository
  String path
  PIPELINE_TEMPLATE template
}
Resource <|-- Pipeline
SourceRepository "1" o-- "0..*" Pipeline


enum PIPELINE_TEMPLATE {
    - JAVA_LIBRARY
    - PYTHON_SERVICE
    - JAVA_SERVICE
    - PYTHON_LIBRARY
    - HELM_PACKAGE
    - DOCKER_SERVICE
    - TERRAFORM_ENVIRONMENT
    - ANSIBLE_ENVIRONMENT
}


class Build {
  String buildNumber
  String path
  String commitLabel
  String commitId
  Long creationDate
  Integer duration
  BUILD_STATUS status
  ListOfBuildArgument buildArguments
  String logs
}
Build "1" o-- "0..*" BuildArgument

class BuildArgument {
  String key
  String value
}

enum BUILD_STATUS {
  - scheduled
  - processing
  - success
  - failed 
}
@enduml