@startuml
class User {
  String firstName
  String lastName
  String email
  String password
  String phone
  ListOfAssignation groups
}
User  "1" o-- "0..*"  Assignation  : assignations
Resource <|-- User
@enduml