@startuml

class  Resource {
  String id
  String name
  MapOfObject metadata
  RESOURCE_STATUS status
  String createdBy
  String updatedBy
  Integer createdAt
  Integer updatedAt
}

enum RESOURCE_STATUS {
         - PENDING
         - READY
         - UPDATING
         - UNSTABLE
         - ERROR
         - DELETED
}

@enduml