@startuml

class  CatalogEntryVersion {
     string version
}

class  CatalogEntryArgument {
     string label
     string description
     string key
     string value
     string constraint
}
CatalogEntryVersion  "0..*" --o "1" CatalogEntryArgument

@enduml