@startuml

class CatalogEntryPackage {
     CatalogEntry catalogEntry
     PACKAGE_TYPE packageType
     String provider
     String providerId
     String url
     ListOfCatalogEntryPackageVersion versions
}
CatalogEntryVersion "1" --o  "0..*" CatalogEntryPackage
CatalogEntry "1" --o  "0..*" CatalogEntryPackage


enum PACKAGE_TYPE {
     - HELM
     - KUSTOMIZE
     - APT
     - SNAP
}

Asset <|-- CatalogEntryPackage

class PackageTemplate {
     string name
     ListOfPackageTemplateArgument arguments
}

class PackageTemplateArgument {
     string key
     string value
     string constraint
}
PackageTemplate "1" --o  "0..*" PackageTemplateArgument


@enduml