@startuml

class  CatalogEntryPackage {
     PACKAGE_TYPE packageType
     string packaprovidergeType
     string packagproviderIdeType
     string url
}
CatalogEntryVersion "1" --o  "0..*" CatalogEntryPackage

enum PACKAGE_TYPE {
     - HELM
     - KUSTOMIZE
     - APT
     - SNAP
}

Asset <|-- CatalogEntryPackage

@enduml