@startuml

class  Group {
  String path
  Group parent
  RESOURCE_STATUS sourceRepositoryStatus
  RESOURCE_STATUS sourceMembershipStatus
  RESOURCE_STATUS pipelineFolderStatus
  RESOURCE_STATUS binaryRepositoryStatus
}
Group  o-- "0..1"   Group : parent
Group  "1" <--   User : technicalUser
Assignation  "1" o-- "0..*"   Group : assignations
Group  "1" <-- "0..1"   KeyPair : group

enum MEMBERSHIP_ROLE {
         - GUEST
         - CONTRIBUTOR
         - MANAGER
}
enum MEMBERSHIP_MEMBERTYPE {
         - USER
         - GROUP
}
class  Membership {
  String path
  MEMBERSHIP_ROLE role
  MEMBERSHIP_MEMBERTYPE memberType
  String memberName
}


class Assignation {
  String role
  String fte
}
Resource <|-- Assignation
@enduml