@startuml

class Cluster {
     String providerId
     String provider
     PACKAGE_TYPE packageManagerManaged
}
RuntimeEnvironment  "1" --o "0..*" Cluster
Resource <|-- Cluster

class RuntimeEnvironment {
     String providerId
     String provider
     String description
     String labels
     User owner
}
Resource <|-- RuntimeEnvironment
Group  "1" o-- "0..*" RuntimeEnvironment : owner
User "1" o-- "0..*" RuntimeEnvironment : owner

RuntimeAppInstance  "1" --o "0..*" RuntimeEnvironment
class RuntimeAppInstance {
     String providerId
     String name
     RuntimeAppInstanceStatus status
}

RuntimeJob  "1" --o "0..*" RuntimeEnvironment
class RuntimeJob {
     String providerId
     RuntimeAppInstanceStatus status
}
enum RuntimeJobStatus {
    SCHEDULED
    RUNNING
    SUCCESS
    FAILED
}


enum RuntimeAppInstanceStatus {
    DEPLOYED
    PENDING
    FAILED
}

RuntimeAppService  "1" --o "0..*" RuntimeEnvironment
class RuntimeAppService {
     String name
     String providerId
     MapOfObject status
}

RuntimeVolume  "1" --o "0..*" RuntimeEnvironment
class RuntimeVolume {
     String name
     String providerId
     String space
     RuntimeJobStatus status
}
enum RuntimeVolumeStatus {
    PROVISIONING
    AVAILABLE
    TERMINATING
}

enum RuntimeContainerStatus {
    CREATING
    RUNNING
    PAUSED
    TERMINATING
    EXIT_WITH_SUCCES
    EXIT_WITH_ERROR
}

RuntimeContainer  "1" --o "0..*" RuntimeEnvironment
class RuntimeContainer {
     String name
     String providerId
     String image
     String imageHash
     String memoryLimit
     String cpuLimit
     RuntimeContainerStatus status
}

RuntimeEnvironmentBackup  "1" --o "0..*" RuntimeEnvironment
class RuntimeEnvironmentBackup {
     String date
     String providerId
     String status
}
enum RuntimeEnvironmentBackupStatus {
    SCHEDULED
    PROCESSING
    DONE
    FAILED
}

RuntimeHttpLoadBalancer  "1" --o "0..*" RuntimeEnvironment

class RuntimeHttpLoadBalancer {
     String name
     String providerId
     String hostname
     String port
     String rewriteUrl
}
RuntimeHttpLoadBalancerForwarding  "1" --o "0..*" RuntimeHttpLoadBalancer

class RuntimeHttpLoadBalancerForwarding {
     String rule
     String service
     String port
}

CatalogEntryPackage  "0..*" --o "1" RuntimeAppInstance
@enduml