@startuml

class CatalogEntry {
     PACKAGE_TEMPLATE packageTemplate
     ListOfCatalogEntryPackage packages
     string description
}

enum PACKAGE_TEMPLATE {
     - REST_SERVICE
}
CatalogEntryPackage  "0..*" --o "1" CatalogEntry

Resource <|-- CatalogEntry
Asset  "0..*" --o "1" CatalogEntry



@enduml