@startuml

class  CatalogEntry {
     PACKAGE_TEMPLATE packageTemplate
     string icon
}

enum PACKAGE_TEMPLATE {
     - REST_API
}
CatalogEntry  "0..*" --o "1" CatalogEntryPackage

Resource <|-- CatalogEntry
Asset  "0..*" --o "1" CatalogEntry

@enduml